MODEL:
  IMG_CHANNELS: 3
  NUM_HID_CHANNELS: 64
  NUM_RESIDUALS: 9

DATASET:
  IMG_SIZE: 512
  STATS:
    - - 0.5
      - 0.5
      - 0.5
    - - 0.5
      - 0.5
      - 0.5
  BATCH_SIZE: 32
  VAL_SIZE: 0.1

TRAINING:
  NUM_EPOCHS: 30
  LR: 0.0003
  BETAS:
    - 0.5
    - 0.999