MODEL:
  IMG_CHANNELS: 3
  NUM_HID_CHANNELS: 64
  NUM_RESIDUALS: 9

DATASET:
  IMG_SIZE: 256
  STATS:
    - - 0.5
      - 0.5
      - 0.5
    - - 0.5
      - 0.5
      - 0.5
  BATCH_SIZE: 8

TRAINING:
  NUM_EPOCHS: 70
  MIN_LR: 0.000003
  LR_GEN: 0.0003
  LR_DIS: 0.00003
  LR_RED_FACTOR: 0.9
  START_RED_LR: 35
  BETAS:
    - 0.5
    - 0.999
  LAMBDA_CYCLE: 10
  IDT_COEF: 0.5