MODEL:
  IMG_CHANNELS: 3
  NUM_HID_CHANNELS: 64
  NUM_RESIDUALS: 9

DATASET:
  IMG_SIZE: 256
  STATS:
    - - 0.5
      - 0.5
      - 0.5
    - - 0.5
      - 0.5
      - 0.5
  BATCH_SIZE: 16

TRAINING:
  NUM_EPOCHS: 30
  LR: 0.0002
  BETAS:
    - 0.5
    - 0.999
  LAMBDA_CYCLE: 10